### ISSUE TITLE
New Methods

### ISSUE THREAD

**Issue by deeepeshthakur** [deeepeshthakur/OrdinaryDiffEq.jl#2]
Here are some additional articles describing/investigating/developing Runge-Kutta methods, especially for hyperbolic PDEs:

* [x]  [Higueras, Roldan (2019)](https://arxiv.org/abs/1809.04807) #581 #584 and missing the last.
* [ ]  [Conde, Fekete, Shadid (2018)](https://arxiv.org/abs/1806.08693) (adaptive)
* [ ]  [Kubatko, Yeager, Ketcheson (2014)](https://link.springer.com/article/10.1007%2Fs10915-013-9796-7)
* [x]  [Parsani, Ketcheson, Deconinck (2013)](https://epubs.siam.org/doi/10.1137/120885899) #648 The 2nd and 3rd other methods are still missing.
* [x]  [Niegemann, Diehl, Busch (2012), especially Table 3](https://www.sciencedirect.com/science/article/pii/S0021999111005213) #611, #614, #616
* [x]  [Bernardini, Pirozzoli (2009)](https://www.sciencedirect.com/science/article/pii/S0021999109001077) #600
* [x]  [Tselios, Simos (2007)](https://www.sciencedirect.com/science/article/pii/S0375960106016951) #637
* [x]  [Toulorge, Desmet (2012)](https://www.sciencedirect.com/science/article/pii/S0021999111006796) #641, #642, #644
* [x]  [Berland, Bogey, Bailly (2006)](https://www.sciencedirect.com/science/article/pii/S0045793005000575) #598
* [x]  [Calvo, Franco, Randez (2004)](https://www.sciencedirect.com/science/article/pii/S0021999104001913) #607
* [ ]  [Kennedy, Carpenter, Lewis (2000)](https://www.sciencedirect.com/science/article/pii/S0168927499001415)
* [ ]  [Mead, Renaut (1999)](https://www.sciencedirect.com/science/article/pii/S0021999199962605)
* [ ]  [Stanescu, Habashi (1998)](https://www.sciencedirect.com/science/article/pii/S0021999198959861) #596
* [ ]  [Hadjimichael, Ketcheson, Lóczi, and Németh (2016)](https://epubs.siam.org/doi/10.1137/15M101717X) (multistep, adaptive)

These methods do not necessarily have high-priority but may be implemented. There are also many other methods.
